apiVersion: apps/v1
kind: Deployment
metadata:
  name: mz-http
  namespace: mzname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mz-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mz-app
    spec:
      containers:
      - name: app
        image: mohsenzia/mzhttp:1.2
        ports:
        - containerPort: 80
